### ISSUE TITLE
Investigate Cairo 1 runner

### ISSUE THREAD

**Issue by cicr99** [NethermindEth/cairo-vm-go#620]
There should be a few differences between cairo zero runner and the one for cairo 1. These will dictate whether we can reuse some of our current code. There are two important things we need to check:

- [ ]  Check instructions. Check whether there are differences in the way to decode the instructions or how a specific instruction is supposed to change the state
- [ ] Check pipeline. I'm interested here in checking the initialization of all the segments, if there are any particular constraints we need to follow, execution of builtins and hints. Take a look at function `run_function_with_starknet_context` [here](https://github.com/starkware-libs/cairo/blob/3540731e5b0e78f2f5b1a51d3611418121c19e54/crates/cairo-lang-runner/src/lib.rs#L239) which is called from [here](https://github.com/starkware-libs/cairo/blob/3540731e5b0e78f2f5b1a51d3611418121c19e54/crates/bin/cairo-run/src/main.rs#L89).

Write a comment in this issue outlining all the info you gather about each of this, so we can then create specific tasks to work on.

**Comment by Sh0g0-1758** [comment]
# Cairo One Runner Write Up

To start off, I found some new builtins in Cairo one.

- [x]   Output 
- [x]  Pedersen 
- [x]  Range Check 
- [x]   ECDSA 
- [x]   Bitwise 
- [x]  EC OP 
- [x]   Keccak 
- [x]   Poseidon 
- [ ]  Range Check96 
- [ ]   AddMod 
- [ ]   MulMod 
- [ ]  Segment Arena 
- [ ]  Gas
- [ ] System

We will also have to add support for sierra in the VM. The cairo one runner's struct have these extra variables : 

```
    /// The sierra program.
    sierra_program: cairo_lang_sierra::program::Program,
    /// Metadata for the Sierra program.
    metadata: Metadata,
    /// Program registry for the Sierra program.
    sierra_program_registry: ProgramRegistry<CoreType, CoreLibfunc>,
    /// Program registry for the Sierra program.
    type_sizes: TypeSizeMap,
    /// The casm program matching the Sierra code.
    casm_program: CairoProgram,
    /// Mapping from class_hash to contract info.
    starknet_contracts_info: OrderedHashMap<Felt252, ContractInfo>,
```

In the runner, we will have to introduce some new functions : 

1. get_initial_available_gas : Returns the initial value for the gas counter. In case there are not any costs - it means no gas equations were solved (and we are in the case of no gas checking enabled) - so the gas builtin is irrelevant, and we can return any value.
2. create_entry_code and create_code_footer : Returns the instructions to add to the beginning of the code to successfully call the main function, as well as the builtins required to execute the program.
3. assemble_ex : Creates an assembled representation of the program preceded by `header` and followed by `footer`.
4. There is also a separate HintProcessor which is required to run through the hints before the vm executes it. This is preceded by a `build_hints_dict` function which register hint with string for the hint processor. Its struct is : 

```
pub struct CairoHintProcessor<'a> {
    /// The Cairo runner.
    pub runner: Option<&'a SierraCasmRunner>,
    /// A mapping from a string that represents a hint to the hint object.
    pub string_to_hint: HashMap<String, Hint>,
    /// The starknet state.
    pub starknet_state: StarknetState,
    /// Maintains the resources of the run.
    pub run_resources: RunResources,
    /// Resources used during syscalls - does not include resources used during the current VM run.
    /// At the end of the run - adding both would result in the actual expected resource usage.
    pub syscalls_used_resources: StarknetExecutionResources,
}
```
5. run_function : Runs the vm starting from a function with custom hint processor. Function may have implicits, but no other ref params. The cost of the function is deducted from `available_gas` before the execution begins.
6. After we initialize the vm, we add a builtin_cost segment but I am not really sure about what that means / do. 

# Cairo one VM changes : 

Most of the code for the VM can be reused. There are a few changes required : 

1. Support for the missing builtins that I mentioned above.
2. There is a new relocation rule in the rust vm : 

```
Will return an error if any of the following conditions are not met:
- Source address's segment must be negative (temporary).
- Source address's offset must be zero.
- There shouldn't already be relocation at the source segment.
```

**Comment by MaksymMalicki** [comment]
I compiled fibonacci.cairo (https://github.com/lambdaclass/cairo-vm/blob/main/cairo_programs/cairo-1-programs/fibonacci.cairo) to sierra and then feed it both to the [sierra-compile-json](https://github.com/zmalatrax/cairo/blob/efa25e40ae62299fdcca0f52ca83d95d0c417699/crates/bin/sierra-compile-json/src/main.rs#L39) command and to the [rust-vm from lambda class](https://github.com/lambdaclass/cairo-vm/blob/main/cairo1-run/src/main.rs). The bytecode in program segment, produced by `sierra-compile-json` is visible on the screen below:
![photo_2024-10-15 11 54 53](https://github.com/user-attachments/assets/a8c40c76-5b05-4f5b-94f9-c438ac7c0665)

and the bytecode produced in lambdaclass cairo-vm is on this screen:
![photo_2024-10-15 11 54 58](https://github.com/user-attachments/assets/c64b902f-87f9-42de-8513-a7d9a61d9bb3)

As you can see they don't really match, also there are some hints present in the json output from `sierra-compile-json`, but the hint list produced in lambda vm is empty. Below I printed out the hints map from [here](https://github.com/lambdaclass/cairo-vm/blob/3fb0344ce038b3a68cae897c403d1f561cfe8da7/cairo1-run/src/cairo_run.rs#L199):
<img width="125" alt="Screenshot 2024-10-15 at 11 57 07" src="https://github.com/user-attachments/assets/ced37d3a-0cd6-489a-a3bd-60feda2b97e4">

Since the generated instructions are clearly not matching, the runner fails on the second step, trying to load hint which (according to lambda class cairo-vm) should not exist. If the bytecode and hints produced by lambda rust-vm are loaded into Nethermind cairo-vm, everything works fine in `execution mode`.

Strange thing I noticed is that the parsed sierra programs in the `sierra-compile-json` and lambdaclass rust-vm are different, eventhough I provide the same `output.sierra` file to both programs. Here is how the `sierra-compile-json` parses the sierra program ([link](https://github.com/zmalatrax/cairo/blob/efa25e40ae62299fdcca0f52ca83d95d0c417699/crates/bin/sierra-compile-json/src/main.rs#L32)) and here is how the rust-vm does it ([link](url)). Furthermore they both produce different CASM programs. I'm going to further investigate this.
